#!/usr/bin/env bash
# Local syntax check for macOS hosts without a full Xcode installation.
#
# The plugin itself is built by CI (Windows is the production platform), but a full CI round trip
# is a slow way to find a typo. This compiles every source with -fsyntax-only against the pinned
# OBS headers and Qt frameworks, which needs neither Xcode nor a libobs build.
#
# Usage: build-aux/syntax-check.sh

set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
deps_dir="${project_root}/.deps-syntax"

obs_version="$(python3 -c 'import json;print(json.load(open("'"${project_root}"'/buildspec.json"))["dependencies"]["obs-studio"]["version"])')"
qt_version="$(python3 -c 'import json;print(json.load(open("'"${project_root}"'/buildspec.json"))["dependencies"]["qt6"]["version"])')"
deps_version="$(python3 -c 'import json;print(json.load(open("'"${project_root}"'/buildspec.json"))["dependencies"]["prebuilt"]["version"])')"

obs_src="${deps_dir}/obs-studio-${obs_version}"
qt_dir="${deps_dir}/qt6-${qt_version}"
prebuilt_dir="${deps_dir}/prebuilt-${deps_version}"

mkdir -p "${deps_dir}"

if [[ ! -d "${obs_src}" ]]; then
    echo "==> fetching OBS ${obs_version} headers"
    curl -fsSL "https://github.com/obsproject/obs-studio/archive/refs/tags/${obs_version}.tar.gz" |
        tar -xz -C "${deps_dir}"
fi

if [[ ! -d "${qt_dir}" ]]; then
    echo "==> fetching Qt6 (obs-deps ${qt_version})"
    mkdir -p "${qt_dir}"
    curl -fsSL "https://github.com/obsproject/obs-deps/releases/download/${qt_version}/macos-deps-qt6-${qt_version}-universal.tar.xz" |
        tar -xJ -C "${qt_dir}"
fi

if [[ ! -d "${prebuilt_dir}" ]]; then
    # libobs headers include <simde/x86/sse2.h>, which ships in the prebuilt obs-deps package.
    echo "==> fetching obs-deps ${deps_version}"
    mkdir -p "${prebuilt_dir}"
    curl -fsSL "https://github.com/obsproject/obs-deps/releases/download/${deps_version}/macos-deps-${deps_version}-universal.tar.xz" |
        tar -xJ -C "${prebuilt_dir}"
fi

# obsconfig.h is generated by the OBS build; a minimal stand-in is enough to parse the headers.
if [[ ! -f "${deps_dir}/generated/obsconfig.h" ]]; then
    mkdir -p "${deps_dir}/generated"
    cat > "${deps_dir}/generated/obsconfig.h" <<'OBSCONFIG'
#pragma once
#define OBS_DATA_PATH "../../data"
#define OBS_PLUGIN_DESTINATION "obs-plugins/64bit"
#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
OBSCONFIG
fi

qt_lib="${qt_dir}/lib"

includes=(
    -I "${project_root}/src"
    -I "${obs_src}/libobs"
    -I "${obs_src}/UI/obs-frontend-api"
    -I "${obs_src}/frontend/api"
    -I "${prebuilt_dir}/include"
    -I "${deps_dir}/generated"
    -F "${qt_lib}"
    -I "${qt_lib}/QtCore.framework/Headers"
    -I "${qt_lib}/QtGui.framework/Headers"
    -I "${qt_lib}/QtWidgets.framework/Headers"
)

status=0
while IFS= read -r source; do
    echo "==> ${source#"${project_root}/"}"
    if ! clang++ -fsyntax-only -std=c++17 -Wall -Wextra "${includes[@]}" "${source}"; then
        status=1
    fi
done < <(find "${project_root}/src" -name '*.cpp' | sort)

if [[ ${status} -eq 0 ]]; then
    echo "==> syntax check passed"
fi
exit ${status}
